In [5]:
import numpy as np

def sudoku_solver(sudoku_board):
    for row in range(9):
        for col in range(9):
            if sudoku_board[row][col] == 0:
                allowed_numbers = set(range(1, 10))
                for cntr in range(9):
                    allowed_numbers -= {sudoku_board[row][cntr]}
                    allowed_numbers -= {sudoku_board[cntr][col]}
                box_row_start = (row // 3) * 3
                box_col_start = (col // 3) * 3
                for box_row in range(box_row_start, box_row_start + 3):
                    for box_col in range(box_col_start, box_col_start + 3):
                        allowed_numbers -= {sudoku_board[box_row][box_col]}
                for allowed_number in allowed_numbers:
                    sudoku_board[row][col] = allowed_number
                    if sudoku_solver(sudoku_board):
                        return True
                sudoku_board[row][col] = 0
                return False
    return True

sudoku_board = np.array([
    list(map(int, '108900040')),
    list(map(int, '043800027')),
    list(map(int, '000000000')),
    list(map(int, '000107002')),
    list(map(int, '009042006')),
    list(map(int, '724060310')),
    list(map(int, '001605974')),
    list(map(int, '800700001')),
    list(map(int, '067219805'))
])

print(sudoku_board)
print()
if sudoku_solver(sudoku_board):
    print(sudoku_board)
else:
    print('No solution exists!')

[[1 0 8 9 0 0 0 4 0]
 [0 4 3 8 0 0 0 2 7]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 7 0 0 2]
 [0 0 9 0 4 2 0 0 6]
 [7 2 4 0 6 0 3 1 0]
 [0 0 1 6 0 5 9 7 4]
 [8 0 0 7 0 0 0 0 1]
 [0 6 7 2 1 9 8 0 5]]

[[1 7 8 9 2 6 5 4 3]
 [9 4 3 8 5 1 6 2 7]
 [6 5 2 4 7 3 1 9 8]
 [3 8 6 1 9 7 4 5 2]
 [5 1 9 3 4 2 7 8 6]
 [7 2 4 5 6 8 3 1 9]
 [2 3 1 6 8 5 9 7 4]
 [8 9 5 7 3 4 2 6 1]
 [4 6 7 2 1 9 8 3 5]]
